name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitHub Pages structure
        run: |
          # Create a temp directory for the built site
          mkdir -p _site
          
          # Copy all files except 'pages' folder
          cp -r js css partials data _site/
          
          # Copy contents of pages directory to the root of _site
          cp -r pages/* _site/
          
          # Fix paths in HTML files
          find _site -name "*.html" -exec sed -i 's|href="/css/|href="./css/|g' {} \;
          find _site -name "*.html" -exec sed -i 's|src="/js/|src="./js/|g' {} \;
          find _site -name "*.html" -exec sed -i 's|href="/pages/|href="./|g' {} \;
          find _site -name "*.html" -exec sed -i 's|src="/partials/|src="./partials/|g' {} \;
          find _site -name "*.html" -exec sed -i 's|href="/data/|href="./data/|g' {} \;
          find _site -name "*.html" -exec sed -i 's|src="/data/|src="./data/|g' {} \;
          
          # Fix paths in JavaScript files
          find _site -name "*.js" -exec sed -i 's|import .* from "/js/|import * from "./|g' {} \;
          find _site -name "*.js" -exec sed -i 's|from "/js/|from "./|g' {} \;
          find _site -name "*.js" -exec sed -i 's|"/js/|"./|g' {} \;
          find _site -name "*.js" -exec sed -i 's|"/css/|"./css/|g' {} \;
          find _site -name "*.js" -exec sed -i 's|"/partials/|"./partials/|g' {} \;
          find _site -name "*.js" -exec sed -i 's|"/data/|"./data/|g' {} \;
          find _site -name "*.js" -exec sed -i 's|"/pages/|"./|g' {} \;
          
          # Debug - List what's in _site directory
          echo "Contents of _site directory:"
          ls -la _site/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: _site
          branch: gh-pages
          clean: true
          single-commit: true
