name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Or your default branch name
  workflow_dispatch:    # Allow manual trigger

permissions:
  contents: write       # Add explicit permissions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages structure
        run: |
          # Create a temp directory for the built site
          mkdir -p _site
          
          # Copy all files except 'pages' folder
          cp -r js css partials data _site/
          
          # Copy contents of pages directory to the root of _site
          cp -r pages/* _site/
          
          # Copy any other important files from root (if needed)
          # cp README.md _site/ 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1  # Specify a precise version
        with:
          folder: _site
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic token
